site_name: 千代雪のノート
site_url: https://chiyoyuki.github.io/

# 以下为仓库信息
repo_url: https://github.com/chiyoyuki/chiyoyuki.github.io/
repo_name: chiyoyuki/chiyoyuki.github.io/

theme:
  language: zh
  name: material # 设定主题为 material
  # custom_dir: overrides # 启用评论需要此行
  palette: #日夜模式切换
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue #基调色
      accent: pink #强调色
      toggle:
        icon: material/weather-sunny
        name: 让夜幕降下来吧
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo #基调色
      accent: red #强调色
      toggle:
        icon: material/weather-night
        name: 让太阳升起来吧
  icon:
    repo: fontawesome/brands/github # 设置git仓库图标
  features:
    - content.code.copy # 启用代码块复制按钮，尽管我觉得用不上
    - navigation.footer # 启用页尾上一页下一页按钮
    - navigation.instant # 内部链接即时加载
    - navigation.tabs # 页顶导航栏
    - navigation.tabs.sticky # 粘性导航栏
    - navigation.top # 回到顶部
    - toc.follow # 边栏自动滚动

plugins:
  - search

markdown_extensions: # markdown扩展插件
  - admonition # 启用注释语法扩展
  - pymdownx.arithmatex: # 数学公式支持
      generic: true
  - pymdownx.caret # 下划线与上标
  - pymdownx.details # 启用注释语法扩展
  - pymdownx.mark # 强调
  - pymdownx.superfences # 启用注释语法扩展
  - pymdownx.tilde # 删除线与下标
  - meta #waline需要，参见https://github.com/squidfunk/mkdocs-material/discussions/4166

extra_javascript: #js文件
  - javascripts/mathjax.js # 数学公式支持
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # 数学公式支持

nav:
  - "index.md"
  - 有关该网站:
    - "time.md"
  - 临时博客:
    - "blog/index.md"
  - 数学:
    - 抽象代数:
      - "Abstract_Algebra/index.md"
      - "Abstract_Algebra/0.md"
  #   - 线性代数:
  #     - "Linear_Algebra/index.md"
  #   - 离散数学:
  #     - "Discrete_Mathematics/index.md"
  #   - 初等数论:
  #     - "Number_Theory/index.md"
  #   - 微积分:
  #     - "Calculus/index.md" 
  #   - 常微分方程:
  #     - "ODE/index.md"
  #   - 数学物理方法:
  #     - "Mathematical_Physics/index.md"
  #   - 偏微分方程: 
  #     - "PDE/index.md"
  #   - 微分方程数值解:
  #     - "Numerical_Solutions_of_PDE/index.md"
  #   - 微分几何:
  #     - "Differentual_Grometry/index.md"
  #   - 拓扑学基础:
  #     - "Topology/index.md"
    - 实变函数:
      - "Real_Analysis/index.md"
      - "Real_Analysis/1.md"
      - "Real_Analysis/2.md"
      - "Real_Analysis/3.md"
      - "Real_Analysis/4.md"
      - "Real_Analysis/5.md"
      - "Real_Analysis/6.md"
  #   - 泛函分析:
  #     - "Function_Analysis/index.md"
  #   - 概率统计:
  #     - "Probability_and_Statistics/index.md"
  #   - 随机过程: 
  #     - "Stochastic_Process/index.md"
  # - 物理学: 
  #   - 力学:
  #     - "Mechanics/index.md"
  #   - 电磁学: 
  #     - "Electricity_Magnetism/index.md"
  #   - 波动学:
  #     - "Waves/index.md"
  - 计算机:
  #   - 工具:
  #     - "Missing_Semester/index.md"
  #   - 数字电路:
  #     - "Logic_Circuit/index.md"
  #   - 计算机系统:
  #     - "CSAPP/index.md"
  #   - 计算机体系结构:
  #     - "Computer_Architecture/index.md"
  #   - 数据结构与算法:
  #     - "DS_and_A/index.md"
  #   - 计算机网络:
  #     - "Computer_Network/index.md"
  #   - 操作系统:
  #     - "Operating_System/index.md"
  #   - 信息论:
  #     - "Information_Theory/index.md"
    - Web 开发:
      - "Web/index.md" 
      - "Web/1.md" 
  - 日语:
    - "Japanese/index.md"

