= Number Theorem 9th note

=== Artin's Conj.

Original form: $a != -1 "sq. free"$, $exists inf$ many $p$ such $a$ is a primitive root $mod p$.

$ C=product_p (1-1/(p(p-1)))=0.3739... $

*Problem*

Suppose that $p,q>0$ are odd primes with $q=4p+1$.\
Prove that $2$ is a primitive root $mod q$. (HW)

=== Theorem 9.1

The group $U_n$ is cyclic iff $n=1,2,4,p^e," or "p^(2e)$, where $p$ is an odd prime.

==== Pf.

===== $(arrow.l.double)$

We only left with the case $n=2p^e$.\
By the multiplicativity, $phi(2p^e)=phi(2)phi(p^e)=phi(p^e)$.
Let $g$ be a primitive root $mod p^e$, then so is $g+p^e$.
One of $g$ and $g+p^e$ must be odd.
So we have an odd primitive root $h mod p^e$.
We claim $h$ is a prim. root $mod 2p^e$.
By its construction, $h$ is coprime to 2 and p.
So $h$ is a unit $mod p^e$, we have that $phi(p^e)|i$.
But $phi(2p^e)=phi(p^e)$, so $phi(2p^e)|i$.
Therefore, $h$ has order $phi(2p^e)$ in $U_(2p^e)$, and thus a prim. root.

===== $(=>)$

If $n!=1,2,3,p^e" or "2p^e$, then we must in one of the followity:
+ $n=2^e (e>=3)$
+ $n=2^e dot p^f (e>=2,f>=1" and "p" odd prime")$
+ $n$ is divisible by at least two odd primes.

In case (1), $U_n$ is now cyclic by Prof. 8.13.
Case (2) and (3) are covered Lemma 8.17.

Recall Corollary 7.8 and now the structure of $U_(p^e)$ is known.

=== Corollary 9.2

If $2^f||n$, then
$
  U_n tilde.rev.equiv cases(
    C_2 times C_(2^(f-2)) times product_(p^e||n)C_(p^(e-1)(p-1)),
    product_(p^e||n)C_(p^(e-1)(p-1))
  )
$

=== Remark 9.3

One can further factonze $C_(p^(e-1)(p-1))$.
In general, we have $ C_m tilde.rev.equiv product_(p^e||m) C_(p^e) $

*HW: Solve the congruence $x^5 equiv 7 mod 18$.*

*HW: Find an integer which is a primitive root $mod 2 dot 11^e$ for all $e>=1$.*

=== Def 9.4.

The exponent $e(G)$ of a finite group $G$ is the least integer $e>0$ such that $a^e=1$ forall $a in G$.
The exponent $e(U_n)$ is called the universal exponent of $n$, denoted by $e(n)$.

By Lagrange's theorm $e(G)| abs(G)$ so $e(n)|phi(n)$.

=== Lemma 9.5

The exponent of product of cyclic groups is the lcm of their orders.

=== Ex. 9.6

$U_1000 tilde.rev.equiv C_2 times C_2 times C_100 tilde.rev.equiv C_2 times C_2 times C_4 times C_25\
=> e(1000)= "lcm"(...)=100$

Find the least three digits of $3^1001$ ?(cf. $phi(1000)=400$)

=== Theorem 9.7 (Korselt)

If $n$ is a Carmichael number, then $n$ is a square-free and $p-1$ divides $n-1$ for each $p$ dividing $n$.

==== Pf.

If $n$ is a Carmichael, then by def $a^(n-1)equiv 1 mod n, forall a in ZZ$.\
So $e(n)|(n-1)$.
If $p^f||n$, then $e(n)$ is divisible by $e(p^f)$\
$e(p^f)=phi(p(f))=p^(f-1)(p-1)$, so $p-1|n-1$.
If $f>1$, then $p|n-1$ as well.
But this is impossible since $p|n$.
Hence $f$ is at most $1$.

*HW: 6.18, 6.20.*

*HW: Find all $a$ such that $x mapsto x^a$ is a ring isomorphism for $ZZ_11$.*

== 9.1

One motivation. Solve quadratic equastions in $ZZ_n$.
Assume that $gcd(2a, n)=1$.
The quadratic congruence $a x^2+b x+c equiv 0 (mod n)$ has a solution iff $Delta = b^2 - 4 a c$ admits a square root $s$ in $ZZ_n$.
In this case, the original form $x=(-b plus.minus sqrt(Delta))/(2a)$ can be interperted as $(-b plus.minus s)(2a)^(-1)$.

=== Def 9.8

An element $a in U_n$ is a quadratic residue $mod n$ if $a=s^2$ for some $s in U_n$; the set of such quad. res. is denoted by $Q_n$.

==== Rmk:

If $S$ exists in $ZZ_n$, then $S$ must be in $U_n$ because
$ 1 equiv a dot a^(-1) = s^2 dot a^(-1) = s dot (s dot a^(-1)) $

=== Ex. 9.9

$Q_11={1,4,9,5,3}, Q_12={1}$

The number of the square root of $a in Q_n$ does not depend on $a$.
Suppose that $s^2=a$ for some $s in U_n$, then we can write any $t in U_n$ as $t=s dot x$ for some unique $x in U_n$.
Then $t^2=a$ is equivalent to $x^2=1 mod n$.
The number $N$ of solutions for $x^2=1$ is given by Example 5.3.\
So $abs(Q_n) dot N = |U_n| => |Q_n|=phi(n)/N$.

=== Lemma 9.10

$Q_n$ is a subgroup of $U_n$.
Moreover, the map $theta: U_n -> Q_n$ given by $theta(s)=s^2$ is an eprodmorphism (=homomorphism + surjection).

==== Pf.

Check that $Q_n$ contains $1$ and closed under product, inverse.
Checking the map is a homomorphism.(all easy!)

=== Rmk 9.11

The kernel $"Ker"theta$ of $theta$ is exactly the set of solutions to $x^2 equiv 1 mod n$.
We have an isomorphism $U_n\/"Ker"theta tilde.rev.equiv Q_n$, which also explains $abs(Q_n)=phi(n)/N$.

=== Lemma 9.12

Let $n=n_1 n_2 dots n_k$ where the integer $n_i$ are mutually coprime.
Then $a in Q_n$ iff $a in Q_(n_i)$ for each $i$.

==== Pf.

The decomposition $U_n tilde.rev.equiv U_(n_1) times U_(n_1) times dots times U_(n_k)$ restricts to the subgroup $Q_n$.\
This is because an element in $U_n$ is a square iff each of its components in $U_n$ is a square.

=== Lemma 9.13

Suppose that there is a primitive root $g mod n$ for $n > 2$.
The $Q_n$ is also cyclic group of $phi(n)/2$ generated by $g^2$.

==== Pf.

The condition $n>2$ ensure that $phi(n)$ is even.
We claim that $Q_n$ precisely consists of elements of the form $g^(2i)$.
Clearly $g^(2i) in Q_n$.
Conversely, if $a in Q_n$, then $a=(g^j)^2$.
Hence, $Q_n$ is generated by $g^2$ (and has order $phi(n)/2$).

=== Lemma 9.14

Let $p$ be an odd prime.
Then $a in Q_(p^e)$ iff $a in Q_p$.

==== Pf.

We know from Theorem 9.1 that there is a primitive root $g mod p^e$.
So $Q_(p^e)$ consists of even powers of $g$.
But $g$ is also a prim. root $mod p$.
So $Q_p$ also consists of even powers of $g$.

=== Lemma 9.15

Let $a$ be an odd integer. Then
+ $a in Q_2$
+ $a in Q_4 "iff" a equiv 1 mod 4$
+ $a in Q_(2^e)(e>=3) "iff" a equiv 1 mod 8$

==== Pf.

(1) and (2) are easy to be verified.
For (3) we may write $a=plus.minus 5^i$ according Prop. 8.13.
So quad. res. are of the form $5^(2i)$.
Since $5^2 equiv 1 mod 8, 5^(2i) equiv 1 mod 8$.

Both $5^i$ and the elements $a equiv 1 mod 8$ account for exactly one quarter of $U_(2^e)$.
The two sets must be equal.

=== Rmk. 9.16

To explicitly final the square roots of $a in U_(p^e)$, one can use Hensel's Lemma(Theorem 6.11).

*HW: 7.15*

=== Theorem 9.17

Let $a in U_n$. Then $a in Q_n$ iff
+ $a in Q_p$ for each odd prime dividing $n$, and
+ $a equiv 1 mod 4$ if $2^2||n$, and $a equiv 1 mod 8$ if $2^3|n$.

==== Pf.

By Lemma 9.12, $a in Q_n$ iff $a in Q_p$ for each prime power $p^e$ in the factorization of $n$.
For odd prime, this is equivalent to $a in Q_p$ by Lemma 9.14.
For $p=2$, it is equivalent to condition (2) by Lemma 9.15.
